name: Deploy to k3s cluster

on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to k3s cluster
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: Create .kube directory
        run: mkdir -p $HOME/.kube

      - name: Configure kubectl
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG_CONTENT }}
        run: echo "${{ secrets.KUBECONFIG_CONTENT }}" | base64 --decode > $HOME/.kube/config

      - name: Verify k3s login
        run: kubectl get nodes

      - name: Deploy to cluster
        run: kubectl apply -f ./manifests/ -R
